### ISSUE TITLE
registerWatchedPartials seems to have stopped working

### ISSUE THREAD

**Issue by JeffML** [dpolivy/hbs-utils#3]
Watched partial stopped working for me.  Not seeing any errors

``` javascript
...
    , hbs = require('hbs')
    , hbsutils = require('hbs-utils')(hbs)
...

hbsutils.registerWatchedPartials(__dirname + '/views/partials', {
    onchange : function(t) {
        logger.info(t + " changed!")             // not seeing this anymore
    },
    precompile : true
}, function() {
    logger.info("partials registered")          //see this
    hbs.registerHelper("debug", function(optionalValue) {
        logger.info("Current Context");
        logger.info("====================");
        logger.info(this);

        if (optionalValue) {
            logger.info("Value");
            logger.info("====================");
            logger.info(optionalValue);
        }
    });

    /*
     *  Special handlebars helper that allows you to pass parameters to a partial
     *
     * Usage:
     * <code>
     * {{include "partialName" param1="value" param2="value" ...}}
     * </code>
     */
    hbs.registerHelper('include', function(template, options) {
        // Find the partial in question.
        var partial = hbs.handlebars.partials[template];

        // Build the new context; if we don't include `this` we get functionality
        // similar to {% include ... with ... only %} in Django.
        var context = _.extend({}, this, options.hash);

        // Render, marked as safe so it isn't escaped.
        return new hbs.handlebars.SafeString(partial(context));
    });

    hbs.registerHelper('toString', function(value, varname) {
        var obj = {};
        if ( typeof (varname) === 'string') {
            obj[varname] = value;
        } else {
            obj = value;
        }
        return escape(JSON.stringify(obj));
    })
    /*
     * help method for formatting numbers to fixed decimal
     */
    hbs.registerHelper('fixed', function(decimals, value) {
        if (value.constructor === String) {
            value = parseFloat(value);
        }

        if ( typeof (value) !== 'number') {
            return 'NaN';
        }

        return value.toFixed(decimals);
    });
}); 
```

$ npm ls -depth=0
userOptionsRepo@0.1.0 /Users/jeff.l/Documents/workspace/responsive-web-design/rwd
├── async@0.9.0
├── body-parser@1.9.2
├── connect-couchdb@1.0.0
├── data2xml@0.9.0
├── express@4.10.1
├── express-session@1.9.1
├── formidable@1.0.15
├── hbs@2.7.0
├── hbs-utils@0.0.3
├── json@9.0.2
├── multer@0.1.6
├── mysql@2.5.2
├── nano@5.12.0
├── request@2.47.0
├── tough-cookie@0.12.1
├── underscore@1.7.0
├── underscore.string@2.3.3
├── winston@0.8.1
└── xml2js@0.4.4

**Comment by jayfresh** [comment]
In case this is relevant, I was using this in Docker with a mounted volume from a Windows host. It wasn't working, so I dug into it and found that the watcher is using node-watch, which wraps fs.watch, which doesn't work for NFS volumes. I'm guessing that docker-mounted volumes are NFS. I've swapped to another implementation of registerWatchedPartials that uses vinyl-fs.watch and this works: https://gist.github.com/jayfresh/fe8416ddce15b2c5038b

**Comment by dpolivy** [comment]
@jayfresh Thanks for the tip! It looks like `vinyl-fs` is using [glob-watcher](https://github.com/wearefractal/glob-watcher) which is ultimately using [gaze](https://github.com/shama/gaze) under the hood. If you want to try using `gaze` directly, I can look at moving the code over to that instead.

**Comment by JeffML** [comment]
I haven's seen this issue in quite awhile.  Closing
