### ISSUE TITLE
Way to have multiple registerWatchedPartials folders

### ISSUE THREAD

**Issue by danielkoch** [dpolivy/hbs-utils#4]
Is there a simple solution for having more than one "watched" partials folder?

**Comment by dpolivy** [comment]
You should be able to call `registerWatchedPartials` multiple times, once for each folder you'd like to register/watch. If that isn't working, let me know.

**Comment by danielkoch** [comment]
Yes, you' right. Thought I tried this. But another question in this context. It is possible to let registerWatchedPartials watch file changes recursive in folders inside the given path?

**Comment by dpolivy** [comment]
I believe it already does that, too. Under the hood, it is using `node-watch`, and based on the [documentation](https://github.com/yuanchuan/node-watch#options), it looks like it defaults to watching recursively. So it should enumerate all files in subfolders that match the partial filename spec.
