### ISSUE TITLE
How to use with `import`?

### ISSUE THREAD

**Issue by NetOpWibby** [dpolivy/hbs-utils#8]
Hi there, I love `hbs-utils` and it's an integral part of my workflow and boilerplates. I've recently started using `import` but I am unsure how to convert `const hbsutils = require("hbs-utils")(hbs);` to something I can import.

Any ideas?

**Comment by dpolivy** [comment]
@NetOperatorWibby Glad to hear this module is helpful for you! I haven't really looked at `import` myself, so I don't have an answer right away, sorry. If it's similar to `require`, can you just `import hbsutils from "hbs-utils"`, and then call `hbsutils(hbs)` once it is loaded?

**Comment by NetOpWibby** [comment]
That works!

I was able to use partials like so:

```
hbsutils(hbs).registerPartials(__dirname + "/system/views/partials");
hbsutils(hbs).registerWatchedPartials(__dirname + "/system/views/partials");
```

Thanks for the suggestion!

**Comment by dpolivy** [comment]
Awesome! I might do something like `var hbs_utils = hbsutils(hbs)` because each time you do call the module constructor, you create a new instance.

**Comment by NetOpWibby** [comment]
Hmm, okay. I'll do that! :)
